Repository Saikat2407/DSA_Hacktoberfest, pull requests merged in 2022-10, with the labels that each got.

#14 Create reverse_words_in_string.cpp
  Leetcode/reverse_words_in_string.cpp
Labels: hacktoberfest, hacktoberfest2022

#12 added parity from hackerank case
  Go/parity/parity.go
Labels: good first issue, hacktoberfest

#15 QuickSort in python
  Python/sorting_algrithms/quick_sort.py
Labels: hacktoberfest, hacktoberfest2022

#16 Create hangman.py
  Python/hangman.py
Labels: hacktoberfest, hacktoberfest2022

#27 Implemented Rotate Image In Python
  Leetcode/rotate_image.py
Labels: hacktoberfest, hacktoberfest2022

#34 Created binarysearch.cpp
  C++/binarysearch.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#35 Added NOBEL.cpp
  CodeChef/NOBEL.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#38 BFS and Reverse string using stack
  C++/BFS.cpp
  C++/reverse_string_using_stack.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#43 added code for path_sum and house_robber
  .vscode/settings.json
  Leetcode/house_robber.cpp
  Leetcode/path_sum.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#44 Create BubbleSort.cpp
  C++/sorting/BubbleSort.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#36 Created Heap Sort
  Java_Imp/sorting/Heap Sort Method
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#60 Fibonacci series in java
  Java_Imp/Easy_level_Program
  Java_Imp/Easy_level_Program/FibonacciExample2.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#62 Scramble_String
  Leetcode/Scramble_String.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#67 Create MergeSort.cpp
  C++/MergeSort.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#69 Create DFS_of_Graph.cpp
  C++/DFS_of_Graph.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#10 PathSum
  Leetcode/Pathsum.cpp
Labels: documentation, good first issue, hacktoberfest

#68 Added algorithm to find shortest path : FloydWarshallAlgo.cpp
  C++/FloydWarshallAlgo.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#73 Counting_Sort.cpp
  c++/sorting/counting_sort.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#90 Insertion Sort using c++
  C++/circularll.cpp
  C++/sorting/insertionSort.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#112 Create 0-1 Knapsack in C++
  C++/0-1 Knapsack
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted
